ALTER TABLE `SaleLeap`.`orders`
ADD COLUMN `ItemId` INT(11) NULL DEFAULT NULL AFTER `updatedAt`,
ADD COLUMN `UserId` INT(11) NULL DEFAULT NULL AFTER `ItemId`,
ADD COLUMN `SellerId` INT(11) NULL DEFAULT NULL AFTER `UserId`;
